
# IGDB API Endpoint variables for use with igdb_request(endpoint, param)
CHARACTERS = "characters/"
COLLECTIONS = "collections/"
COMPANIES = "companies/"
CREDITS = "credits/"
FEEDS = "feeds/"
FRANCHISES = "franchises/"
GAME_ENGINES = "game_engines/"
GAME_MODES = "game_modes/"
GAMES = "games/"
GENRES = "genres/"
KEYWORDS = "keywords/"
PAGES = "pages/"
PEOPLE = "people/"
PLATFORMS = "platforms/"
PLAYER_PERSPECTIVES = "player_perspectives/"
PULSE_GROUPS = "pulse_groups/"
PULSE_SOURCES = "pulse_sources/"
PULSES = "pulses/"
RELEASE_DATES = "release_dates/"
REVIEWS = "reveiws/"
THEMES = "themes/"
TITLES = "titles/"
